# Generated by Django 4.0.1 on 2022-03-10 18:06

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('adapted_title', models.CharField(max_length=200)),
                ('year_of_publication', models.DateField(default=datetime.datetime(2022, 3, 10, 18, 6, 20, 642184, tzinfo=utc), verbose_name='year of publication')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2022, 3, 10, 18, 6, 20, 642184, tzinfo=utc), verbose_name='date published')),
                ('author', models.CharField(max_length=200)),
                ('coutry_of_origin', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('additional_information', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catalog/static/catalog/images')),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=200)),
                ('reading_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.readingmaterial')),
            ],
        ),
    ]
