# Generated by Django 4.0.1 on 2022-02-06 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_title', models.CharField(max_length=200)),
                ('adapted_title', models.CharField(max_length=200)),
                ('first_publication_date', models.DateTimeField(verbose_name='date published')),
                ('author', models.CharField(max_length=200)),
                ('coutry_of_origin', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('additional_information', models.TextField()),
                ('number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender_name', models.CharField(max_length=200)),
                ('reading_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.readingmaterial')),
            ],
        ),
    ]
