# Generated by Django 4.0.1 on 2022-02-06 02:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingmaterial',
            name='first_publication_date',
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 2, 40, 2, 249291, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='readingmaterial',
            name='year_of_publication',
            field=models.DateField(default=datetime.datetime(2022, 2, 6, 2, 40, 2, 249291, tzinfo=utc), verbose_name='year of publication'),
        ),
    ]
