# Generated by Django 4.0.1 on 2022-02-06 02:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_readingmaterial_first_publication_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterial',
            name='additional_information',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 2, 58, 28, 288929, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='year_of_publication',
            field=models.DateField(default=datetime.datetime(2022, 2, 6, 2, 58, 28, 288929, tzinfo=utc), verbose_name='year of publication'),
        ),
    ]
