# Generated by Django 4.0.1 on 2022-02-06 03:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_readingmaterial_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterial',
            name='additional_information',
            field=models.TextField(default='', verbose_name=0),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 6, 3, 3, 11, 974150, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='year_of_publication',
            field=models.DateField(default=datetime.datetime(2022, 2, 6, 3, 3, 11, 974150, tzinfo=utc), verbose_name='year of publication'),
        ),
    ]
