# Generated by Django 4.0.1 on 2022-02-16 14:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_readingmaterial_additional_information_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterial',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 16, 14, 28, 14, 808239, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='year_of_publication',
            field=models.DateField(default=datetime.datetime(2022, 2, 16, 14, 28, 14, 808239, tzinfo=utc), verbose_name='year of publication'),
        ),
    ]
