# Generated by Django 4.0.1 on 2022-03-03 18:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_alter_readingmaterial_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='readingmaterial',
            name='slug',
            field=models.SlugField(default='slug_padrao', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='catalog/static/catalog/images'),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 18, 35, 38, 128900, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='year_of_publication',
            field=models.DateField(default=datetime.datetime(2022, 3, 3, 18, 35, 38, 128900, tzinfo=utc), verbose_name='year of publication'),
        ),
    ]
