# Generated by Django 4.0.1 on 2022-03-03 20:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_readingmaterial_slug_alter_readingmaterial_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterial',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 20, 23, 34, 565844, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='synopsis',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='year_of_publication',
            field=models.DateField(default=datetime.datetime(2022, 3, 3, 20, 23, 34, 565844, tzinfo=utc), verbose_name='year of publication'),
        ),
    ]
