# Generated by Django 4.0.1 on 2022-03-03 20:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0023_alter_readingmaterial_pub_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingmaterial',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 3, 20, 26, 3, 955103, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='synopsis',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='readingmaterial',
            name='year_of_publication',
            field=models.DateField(default=datetime.datetime(2022, 3, 3, 20, 26, 3, 955103, tzinfo=utc), verbose_name='year of publication'),
        ),
    ]
